name: Lint and Test Charts

on:
  workflow_run:
    workflows: ["Docker Build and Deploy"]
    branches:
      - main
    types: 
      - completed

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.9.2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs helm --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check Version
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          python -m pip install -e .
          python -m pip install pyyaml
          python .github/workflows/scripts/check_version.py

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --chart-dirs helm --target-branch ${{ github.event.repository.default_branch }}

      - name: Build container
        uses: docker/build-push-action@v6
        if: steps.list-changed.outputs.changed == 'true'
        with:
          platforms: linux/amd64
          context: .
          file: Dockerfile
          push: false
          tags: "titiler-eopf:dev"
      
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Load container image in kind cluster
        run: kind load docker-image titiler-eopf:dev --name chart-testing
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create Namespace
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create namespace titiler-eopf

      - name: Create Secret
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create secret generic titiler-eopf-secret -n titiler-eopf --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --chart-dirs helm --namespace titiler-eopf
